branches:
  only:
    - master

language: android

android:
  components:
    # Latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.1

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - nvm install node
  - node --version
  - npm install -g ionic cordova

script:
  - npm install
  - ./.ci/build-android.sh && ./.ci/package-android.sh

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file: output/ibp.apk
  skip_cleanup: true
  overwrite: true